---
title: "Selection Response In Beef Cattle"
output: html_notebook
---


## Disclaimer
This notebook can be used for testing functions to compute asymptotic selection responses.

## Debugging
### Proportion of calves
```{r}
pvec_proportion_progeny_adult <- 0.5
pvec_number_progeny <- 20
proportion_calves <- 1 -  pvec_proportion_progeny_adult
proportion_calves
male_number_adults <- floor(pvec_proportion_progeny_adult[[1]]*pvec_number_progeny[[1]])
male_number_adults
male_number_calves <- pvec_number_progeny[[1]] - male_number_adults
male_number_calves
```

### Design matrix $Z_y$ 

```{r}
  pvec_economic_values <- rep(1,6)
  n_r_trait <- length(pvec_economic_values)

  ### ## Building Design Matrix Z
  ### ## Design Matrix for one calf
  male_designMatrix_calf <- cbind(c(1,0,0),c(0,0,0),c(0,1,0),c(0,0,0),c(0,0,1),c(0,0,0))
  ### ## Design Matrix for one adult
  male_designMatrix_adult <- cbind(c(0,0,0),c(1,0,0),c(0,0,0),c(0,1,0),c(0,0,0),c(0,0,1))
  ### ## Design Matrix for calves
  male_designMatrix_calves <- diag(1,male_number_calves)%x%male_designMatrix_calf
  male_designMatrix_calves <- cbind(male_designMatrix_calves,
                                    matrix(0, nrow=nrow(male_designMatrix_calves),
                                              ncol=male_number_adults*n_r_trait))
  ### ## Design Matrix for adults
  male_designMatrix_adults <- diag(1,male_number_adults)%x%male_designMatrix_adult
  male_designMatrix_adults
  dim(male_designMatrix_adults)
  male_designMatrix_adults <- cbind(matrix(0, nrow=nrow(male_designMatrix_adults),
                                           ncol=male_number_calves*n_r_trait),
                                    male_designMatrix_adults)
  male_designMatrix_adults
  dim(male_designMatrix_adults)
  ### ## Bind Design Matrix for calves and adults
  dim(male_designMatrix_calves)
  dim(male_designMatrix_adults)
  male_designMatrixZ <- rbind(male_designMatrix_calves, male_designMatrix_adults)
  ### ## Add selection candidate
  male_designMatrixZ<-cbind(matrix(0, nrow=pvec_number_progeny[[1]]*(n_r_trait/2),ncol=n_r_trait),male_designMatrixZ)
  ### Check Dimension
  dim(male_designMatrixZ)
```

### Residual Matrix
```{r}
## residual
s_residual_var_cov <- "../inst/extdata/variance_component_values/adults_calves_residual_variances_covariances"
df_residual_var_cov <- read.table(file = s_residual_var_cov, sep=";", header=TRUE)
mat_residual_var_cov <- as.matrix(df_residual_var_cov)
pmat_residual_varcov <- mat_residual_var_cov
pmat_residual_varcov

mat_residual_var_cov_calves <- pmat_residual_varcov[c(1,3,5),c(1,3,5)]
mat_residual_var_cov_calves
mat_residual_var_cov_adults <- pmat_residual_varcov[c(2,4,6),c(2,4,6)]
mat_residual_var_cov_adults

male_calves_kronecker_residual <- diag(male_number_calves) %x% mat_residual_var_cov_calves
male_adults_kronecker_residual <- diag(male_number_adults) %x% mat_residual_var_cov_adults
male_calves_kronecker_residual_extended <- cbind(male_calves_kronecker_residual,
                                                 matrix(0,nrow=nrow(male_calves_kronecker_residual),
                                                          ncol=ncol(male_adults_kronecker_residual)))
male_adults_kronecker_residual_extended <- cbind(matrix(0,nrow=nrow(male_adults_kronecker_residual),
                                                           ncol=ncol(male_calves_kronecker_residual)),
                                                male_adults_kronecker_residual)
male_ResidualMatrix <- rbind(male_calves_kronecker_residual_extended,male_adults_kronecker_residual_extended)

```


### Relationship Matrix $A_y$ and Inverse $A_y^{-1}$

```{r RelationshipMatrix}
  mnumb <- pvec_number_progeny[[1]]+1
mnumb
  male_Pedigree <- pedigreemm::pedigree(sire = c(NA,rep(1,times = pvec_number_progeny[[1]])),
                                        dam =c(NA,rep(NA,times = pvec_number_progeny[[1]])),
                                        label = 1:mnumb)
  male_Pedigree
  
  ### ## Compute inverse of relationsship matrix
  male_AInv <- as.matrix(pedigreemm::getAInv(male_Pedigree))
  male_AInv
  dim(male_AInv)
```

### Genetic Variance Covariance Matrix G
```{r}
s_genetic_var_cov <- "../inst/extdata/variance_component_values/adults_calves_genetic_variances_covariances"
df_genetic_var_cov <- read.table(file = s_genetic_var_cov, sep=";", header=TRUE)
pmat_genetic_varcov <- as.matrix(df_genetic_var_cov)
pmat_genetic_varcov

```

### Computation of PEV
```{r}
  male_PEV <- solve(t(male_designMatrixZ)%*%solve(male_ResidualMatrix)%*%male_designMatrixZ+male_AInv%x%solve(pmat_genetic_varcov))
  ### ## Computation of PEV for selection candidate
  male_PEV <- male_PEV[1:n,1:n]

```

### Computation of variance covariance matrix for predicting breeding values
```{r}
  mat_male_var_cov_pbv <- pmat_genetic_varcov - male_PEV

```

